trigger: ["main"]
pr: ["main"]

variables:
  RUSTFLAGS: -Dwarnings
  RUST_VERSION_STABLE: 1.56.1
  RUST_VERSION_NIGHTLY: nightly-2022-07-14

stages:
  - stage: Rust
    jobs:
      - template: ci/azure-install-rust.yml
        parameters:
          rust: $(RUST_VERSION_STABLE)
      - template: ci/azure-lint-rust.yml
        parameters:
          rust: $(RUST_VERSION_STABLE)
      - template: ci/azure-test-rust.yml
        parameters:
          rust: $(RUST_VERSION_STABLE)
      # - template: ci/azure-test-miri.yml
      #   parameters:
      #     rust: $(RUST_VERSION_NIGHTLY)
