trigger: ["main"]
pr: ["main"]

variables:
  RUSTFLAGS: -Dwarnings
  RUST_VERSION_STABLE: 1.56.1
  RUST_VERSION_NIGHTLY: nightly-2022-07-14

stages:
  - stage: Rust
    jobs:
      - job: install_rust
        displayName: 'Install Rust'
        steps:
          - template: ci/azure-install-rust.yml
            parameters:
              version: $(RUST_VERSION_STABLE)

      - job: 'rust_lint'
        displayName: 'Lint Rust'
        pool:
          vmImage: ubuntu-18.04
        steps:
          - template: ci/azure-lint-rust.yml

      - job: 'rust_test'
        displayName: 'Test Rust'
        strategy:
          matrix:
            Linux:
              vmImage: ubuntu-18.04
    
            ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
              MacOS:
                vmImage: macOS-10.15
              Windows:
                vmImage: windows-2019
        pool:
          vmImage: $(vmImage)    
        steps:
          - template: ci/azure-test-rust.yml
