/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

import org.msgpack.core.MessagePacker;
import java.io.IOException;

public class Test {

  private byte[] a = new byte[] {};

  /**
   * Gets a.
   * <p>
   * Default value: new byte[] {}.
   *
   * @return a
   */
  public byte[] getA() {
    return this.a;
  }

  /**
   * Sets the new a.
   *
   * @param a the new a
   * @throws IllegalArgumentException if a contains negative elements
   */
  public void setA(byte[] a) {
    for (byte b : a) {
      if (b < 0) {
        throw new IllegalArgumentException("'a' contains negative numbers");
      }
    }
    this.a = a;
  }

  /**
   * Returns a byte array representation of the current configuration.
   */
  public void pack(MessagePacker __packer) throws IOException {
    __packer.packArrayHeader(1);
    __packer.packInt(this.a.length);
    for (byte __elem_ : this.a) {
      __packer.packByte(__elem_);
    }
  }

  @Override
  public String toString() {
    return "Test{" +
     "a='" + a + '\'' +
     '}';
  }

}
