/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

public class Test {

  private byte[] a = new byte[] {};

  /**
   * Gets a.
   * <p>
   * Default value: new byte[] {}.
   *
   * @return a
   */
  public byte[] getA() {
    return this.a;
  }

  /**
   * Sets the new a.
   *
   * @param a the new a
   * @throws IllegalArgumentException if a contains negative elements
   */
  public void setA(byte[] a) {
    for (byte b : a) {
      if (b < 0) {
        throw new IllegalArgumentException("'a' contains negative numbers");
      }
    }
    this.a = a;
  }

  /**
   * Returns a byte array representation of the current configuration.
   */
  public byte[] asBytes() {
    int __buf__size = 0;
    __buf__size += (a.length * 1);
    __buf__size += 0;
    java.nio.ByteBuffer __buf = java.nio.ByteBuffer.allocate(__buf__size);
    __buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
    __buf.putInt(this.a.length);
    for (byte __elem_ : this.a) {
      __buf.put(__elem_);
    }
    return __buf.array();
  }

  @Override
  public String toString() {
    return "Test{" +
     "a='" + a + '\'' +
     '}';
  }

}
