/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

public class TestAVar extends Test {

  private byte a = 0;

  private int b = 0;

  /**
   * Gets a.
   * <p>
   * Default value: 0.
   *
   * @return a
   */
  public byte getA() {
    return this.a;
  }

  /**
   * Sets the new a.
   *
   * @param a the new a
   * @throws IllegalArgumentException if a is negative
   */
  public void setA(byte a) {
    if (a < 0) {
      throw new IllegalArgumentException("'a' must be positive");
    }
    this.a = a;
  }

  /**
   * Gets b.
   * <p>
   * Default value: 0.
   *
   * @return b
   */
  public int getB() {
    return this.b;
  }

  /**
   * Sets the new b.
   *
   * @param b the new b
   * @throws IllegalArgumentException if b is negative
   */
  public void setB(int b) {
    if (b < 0) {
      throw new IllegalArgumentException("'b' must be positive");
    }
    this.b = b;
  }

  /**
   * Returns a byte array representation of the current configuration.
   */
  @Override
  public byte[] asBytes() {
    int __buf__size = 0;
    __buf__size += 6;
    java.nio.ByteBuffer __buf = java.nio.ByteBuffer.allocate(__buf__size);
    __buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
    __buf.put((byte) 0);
    __buf.put(this.a);
    __buf.putInt(this.b);
    return __buf.array();
  }

}
