/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

import org.msgpack.core.MessagePacker;
import java.io.IOException;

public abstract class Test {

  @Override
  public abstract String toString();

  /**
   * Pack a byte representation of the current configuration.
   */
  public abstract void pack(MessagePacker __packer) throws IOException;

}
