/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

import org.msgpack.core.MessagePacker;
import java.io.IOException;

public class SubclassA extends Superclass {

  private byte a = 0;

  private int b = 0;

  /**
   * Gets a.
   * <p>
   * Default value: 0.
   *
   * @return a
   */
  public byte getA() {
    return this.a;
  }

  /**
   * Sets the new a.
   *
   * @param a the new a
   * @throws IllegalArgumentException if a is negative
   */
  public void setA(byte a) {
    if (a < 0) {
      throw new IllegalArgumentException("'a' must be positive");
    }
    this.a = a;
  }

  /**
   * Gets b.
   * <p>
   * Default value: 0.
   *
   * @return b
   */
  public int getB() {
    return this.b;
  }

  /**
   * Sets the new b.
   *
   * @param b the new b
   * @throws IllegalArgumentException if b is negative
   */
  public void setB(int b) {
    if (b < 0) {
      throw new IllegalArgumentException("'b' must be positive");
    }
    this.b = b;
  }

  /**
   * Returns a byte array representation of the current configuration.
   */
  @Override
  public void pack(MessagePacker __packer) throws IOException {
    __packer.packExtensionTypeHeader((byte) 1, 1);
    __packer.packInt(0);
    __packer.packArrayHeader(2);
    __packer.packByte(this.a);
    __packer.packInt(this.b);
  }

  @Override
  public String toString() {
    return "SubclassA{" +
     "a='" + a + '\'' +
     ", b='" + b + '\'' +
     '}';
  }

}
