/// THIS FILE IS AUTOMATICALLY GENERATED BY THE BYTE BRIDGE LIBRARY.
/// ANY CHANGES MADE MAY BE LOST.
package ai.swim;

public abstract class Superclass {

  /**
   * Returns a byte array representation of the current configuration.
   */
  public abstract byte[] asBytes();

}
