/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_swim_utils_Utils */

#ifndef _Included_ai_swim_utils_Utils
#define _Included_ai_swim_utils_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_swim_utils_Utils
 * Method:    getProcessId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_swim_utils_Utils_getProcessId
  (JNIEnv *, jclass);

/*
 * Class:     ai_swim_utils_Utils
 * Method:    leak
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_swim_utils_Utils_leak
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
