[package]
name = "swim_sys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sys_util = { path = "../sys_util" }
jvm_sys = { path = "../jvm_sys" }
tokio = { version = "1.1.1", features = ["rt-multi-thread", "io-util"] }
jni = "0.19.0"
bytes = "1.1.0"
